// Generated by CoffeeScript 1.6.3
(function() {
  var Dispatcher, Logger, array_make, cache, dispatch, enabled, level, post, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  cache = null;

  enabled = false;

  level = {
    ERROR: 'error',
    WARNING: 'warning',
    INFO: 'info',
    DEBUG: 'debug',
    LOG: 'log'
  };

  Logger = function() {
    return Logger.make();
  };

  if (typeof exports !== "undefined" && exports !== null) {
    if ((typeof module !== "undefined" && module !== null) && module.exports) {
      module.exports = Logger;
    }
    root.Logger = Logger;
  } else {
    if (root.Javie == null) {
      root.Javie = {};
    }
    root.Javie.Logger = Logger;
  }

  array_make = function(args) {
    return Array.prototype.slice.call(args);
  };

  dispatch = function(type, message) {
    if (!enabled) {
      return false;
    }
    return post(type, message);
  };

  post = function(type, message) {
    var c;
    c = console;
    switch (type) {
      case 'info':
        c.info(message);
        return true;
      case 'debug' && (c.debug != null):
        c.debug(message);
        return true;
      case 'warning':
        c.warn(message);
        return true;
      case 'error' && (c.error != null):
        c.error(message);
        return true;
      case 'log':
        c.log(message);
        return true;
      default:
        c.log("[" + (type.toUpperCase()) + "]", message);
        return true;
    }
  };

  Dispatcher = (function() {
    function Dispatcher() {}

    Dispatcher.prototype.logs = [];

    Dispatcher.prototype.dispatch = function(type, message) {
      var result;
      result = dispatch(type, message);
      message.unshift(type);
      this.logs.push(message);
      return result;
    };

    Dispatcher.prototype.info = function() {
      return this.dispatch(level.INFO, array_make(arguments));
    };

    Dispatcher.prototype.debug = function() {
      return this.dispatch(level.DEBUG, array_make(arguments));
    };

    Dispatcher.prototype.warning = function() {
      return this.dispatch(level.WARNING, array_make(arguments));
    };

    Dispatcher.prototype.log = function() {
      return this.dispatch(level.LOG, array_make(arguments));
    };

    Dispatcher.prototype.post = function(type, message) {
      return this.dispatch(type, [message]);
    };

    return Dispatcher;

  })();

  Logger.enable = function() {
    return enabled = true;
  };

  Logger.disable = function() {
    return enabled = false;
  };

  Logger.status = function() {
    return enabled;
  };

  Logger.make = function() {
    if (cache == null) {
      cache = new Dispatcher;
    }
    return cache;
  };

}).call(this);
